name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy mã nguồn
      uses: actions/checkout@v3

    - name: Thiết lập Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cài đặt các thư viện
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Chạy kiểm thử
      run: |
        pytest
